### ISSUE TITLE
Incorrect Temerature Values

### ISSUE THREAD

**Issue by pauldnorth** [ryanbales/FLIRImageProcessor#2]
Hi, 

When analysing the temperature values I'm getting a lot of incorrect values, specifically 7.3913. Please see the screen shot attached. This happens on any image that is loaded. Any ideas?

Thanks

Paul

![flir](https://user-images.githubusercontent.com/20738201/45123513-13620300-b15f-11e8-8470-34374f3c4725.PNG)

**Comment by ryanbales** [comment]
@pauldnorth do you have some example files that you could attach or link?

**Comment by pauldnorth** [comment]
Here you go. Thanks

![flir0197](https://user-images.githubusercontent.com/20738201/45175155-912c1a00-b204-11e8-954f-f8541c7a29b7.jpg)

![flir0197_json](https://user-images.githubusercontent.com/20738201/45175228-ce90a780-b204-11e8-9d03-3d0f09e253bc.jpg)

The second image is the json file. Please rename the file back to .json to view.

Edit: Sorry, here's the zip file. Only just realised I could upload a zip.
[FLIR0197.zip](https://github.com/ryanbales/FLIRImageProcessor/files/2358933/FLIR0197.zip)

**Comment by pauldnorth** [comment]
any joy with a resolution to this problem?

**Comment by pauldnorth** [comment]
Don't worry yourself. I've found the issue.

**Comment by ryanbales** [comment]
@pauldnorth Sorry for the delay.  Can you share the fix and submit a PR?

**Comment by pauldnorth** [comment]
Hi, I just downloaded the latest Atlas (version 5) dlls. It was my new project that wasn't working, I actually havent tested your project with the new dlls so can't upload it I'm afraid. 

Thanks for your initial work as it had pointed me in the right direction for my own project :)

**Comment by ryanbales** [comment]
Thanks @pauldnorth Good luck
